export const events = [
  {
    name: "Conferencia de Desarrollo Web 2025",
    description:
      "Charlas sobre React, Vue, y el futuro del desarrollo frontend.",
    date: "2025-09-15",
    time: "09:00",
    location: "Centro de Convenciones Metropolitano",
    category: "Tecnología",
  },
  {
    name: "Maratón Internacional de la Ciudad",
    description: "Carrera de 42k abierta a corredores de todo el mundo.",
    date: "2025-05-03",
    time: "07:30",
    location: "Punto de partida: Parque Central",
    category: "Deportes",
  },
  {
    name: "Festival Gastronómico 'Sabores del Mundo'",
    description: "Prueba platillos de diferentes culturas con chefs invitados.",
    date: "2025-10-20",
    time: "12:00",
    location: "Plaza de la Alimentación",
    category: "Comida",
  },
  {
    name: "Taller Intensivo de Fotografía Digital",
    description: "Aprende técnicas de composición, iluminación y edición.",
    date: "2025-11-08",
    time: "16:00",
    location: "Estudio Creativo 404",
    category: "Educación",
  },
  {
    name: "Concierto: Banda 'Los Viajeros'",
    description: "Presentación en vivo de su nuevo álbum de rock alternativo.",
    date: "2025-07-26",
    time: "20:30",
    location: "Teatro Principal",
    category: "Música",
  },
  {
    name: "Feria del Libro y la Cultura",
    description:
      "Encuentros con autores, venta de libros y actividades culturales.",
    date: "2025-04-10",
    time: "10:00",
    location: "Explanada de la Universidad",
    category: "Cultura",
  },
  {
    name: "Partido de Fútbol: Clásico Local",
    description:
      "Enfrentamiento entre los dos equipos más grandes de la ciudad.",
    date: "2025-08-17",
    time: "18:00",
    location: "Estadio Olímpico",
    category: "Deportes",
  },
  {
    name: "Seminario de Inversiones en Criptomonedas",
    description:
      "Análisis de mercado, riesgos y oportunidades en el mundo crypto.",
    date: "2025-06-21",
    time: "14:00",
    location: "Sala de Conferencias B",
    category: "Finanzas",
  },
  {
    name: "Noche de Estrellas y Astronomía",
    description: "Observación telescópica guiada y charlas sobre el universo.",
    date: "2025-12-05",
    time: "19:00",
    location: "Observatorio Municipal",
    category: "Ciencia",
  },
  {
    name: "Clase Maestra de Cocina Vegana",
    description: "Aprende a preparar deliciosos platos 100% vegetales.",
    date: "2025-03-01",
    time: "17:00",
    location: "Escuela Culinaria 'El Fogón'",
    category: "Comida",
  },
  {
    name: "Retiro de Yoga y Meditación",
    description: "Tres días de paz y conexión en la naturaleza.",
    date: "2025-09-06",
    time: "10:00",
    location: "Cabañas 'El Bosque'",
    category: "Salud",
  },
  {
    name: "Hackathon 'Innovación Ciudadana'",
    description:
      "Desarrollo de soluciones tecnológicas para problemas urbanos.",
    date: "2025-05-30",
    time: "09:00",
    location: "Incubadora de Empresas Tech",
    category: "Tecnología",
  },
  {
    name: "Obra de Teatro: 'La Máscara Rota'",
    description: "Drama contemporáneo en tres actos.",
    date: "2025-04-22",
    time: "21:00",
    location: "Teatro Experimental",
    category: "Arte",
  },
  {
    name: "Torneo de Videojuegos: League of Legends",
    description: "Competencia regional con un gran premio en efectivo.",
    date: "2025-07-05",
    time: "11:00",
    location: "Arena de eSports",
    category: "Deportes",
  },
  {
    name: "Cata de Vinos Premium",
    description: "Degustación de las mejores cepas nacionales e importadas.",
    date: "2025-10-12",
    time: "19:30",
    location: "Bodega 'El Racimo'",
    category: "Comida",
  },
  {
    name: "Charla: El Impacto de la IA en el Trabajo",
    description:
      "Análisis de cómo la Inteligencia Artificial está cambiando el mercado laboral.",
    date: "2025-03-27",
    time: "18:30",
    location: "Auditorio Principal",
    category: "Tecnología",
  },
  {
    name: "Recorrido Histórico Guiado",
    description: "Paseo a pie por los sitios más emblemáticos de la ciudad.",
    date: "2025-06-08",
    time: "10:30",
    location: "Punto de encuentro: Monumento Central",
    category: "Cultura",
  },
  {
    name: "Clase Abierta de Salsa y Bachata",
    description:
      "Aprende los pasos básicos de estos ritmos latinos. No se necesita pareja.",
    date: "2025-08-01",
    time: "19:00",
    location: "Salón de Baile 'El Ritmo'",
    category: "Música",
  },
  {
    name: "Mercado de Artesanía Local",
    description: "Venta de productos hechos a mano por artesanos de la región.",
    date: "2025-09-28",
    time: "10:00",
    location: "Plaza de las Flores",
    category: "Arte",
  },
  {
    name: "Taller: Primeros Auxilios Básicos",
    description: "Capacitación esencial para responder a emergencias comunes.",
    date: "2025-11-23",
    time: "15:00",
    location: "Cruz Roja Local",
    category: "Educación",
  },
  {
    name: "Exposición de Pintura Moderna",
    description:
      "Muestra de artistas emergentes con enfoque en el arte abstracto.",
    date: "2025-05-18",
    time: "11:00",
    location: "Galería de Arte Contemporáneo",
    category: "Arte",
  },
  {
    name: "Jornada de Adopción de Mascotas",
    description:
      "Encuentra a tu nuevo mejor amigo en este evento de refugios locales.",
    date: "2025-07-13",
    time: "13:00",
    location: "Parque Canino 'La Pata Feliz'",
    category: "Comunidad",
  },
  {
    name: "Caminata Ecológica a la Montaña",
    description:
      "Ruta de senderismo de dificultad media para apreciar la flora y fauna.",
    date: "2025-06-01",
    time: "08:00",
    location: "Reserva Natural 'Cerro Verde'",
    category: "Deportes",
  },
  {
    name: "Webinar Gratuito: Marketing Digital para PYMES",
    description:
      "Estrategias clave para posicionar pequeños y medianos negocios en línea.",
    date: "2025-10-02",
    time: "19:00",
    location: "Online (Zoom)",
    category: "Negocios",
  },
  {
    name: "Proyección de Cortometrajes Independientes",
    description: "Ciclo de cine con producciones locales e internacionales.",
    date: "2025-12-14",
    time: "20:00",
    location: "Cine Club 'Luces'",
    category: "Cultura",
  },
];
